export enum TrackingEvents {
  ADD_TRACKING_MODEL = 'ADD_TRACKING_MODEL',
  REMOVE_TRACKING_MODEL = 'REMOVE_TRACKING_MODEL',
  REMOVE_TRACKING = 'REMOVE_TRACKING',
  CREATE_TRACKING = 'CREATE_TRACKING',
}
